<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Annonce;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\SearchType;
use AppBundle\Form\AnnonceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;


/**
* AnnonceRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function listAction(Request $request)
    {
        // build the form ...
        
        $form->handleRequest($request);
        if ($form->isValid() && $form->isSubmitted()) {
            $data = $form->getData();
            $parameter = $data["recherche"];
            if(!($data['type'])){
                $query = $em->createQuery("select a from AppBundle\Entity\Annonce as a
                where a.titre like :p ")
                ->setParameter('p', '%' . $parameter . '%');
            }else{
                $parameter2 = $data['type']->getId();
                $query = $em->createQuery("select a from AppBundle\Entity\Annonce as a
                join a.typOid as t where t.id = :p2 and
                a.titre like :p   ")
                ->setParameters(array('p' => '%' . $parameter . '%', 'p2' => $parameter2));
            }
            
            $listAnnonces = $query->getResult();
        }
        
        return $this->render('/annonce/liste_annonces.html.twig', array(
            'annonces' => $annonces,
            'form' => $form->createView(),
        ));
    }
}
