<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Annonce;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\SearchType;
use AppBundle\Form\AnnonceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Doctrine\ORM\EntityRepository;


/**
* AnnonceRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
* 
*/
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    // public function findByMotCle()
    // {
    //     //build the form ...
    //     return $this->getEntityManager()
    //     ->createQuery(
    //         'select a from AppBundle\Entity\Annonce as a where a.titre like :p' 
    //         )
    //         ->getResult();
    //     }
        
    //     public function listAction()
    //     {
    //         $annonce = $this->getDoctrine()
    //         ->getRepository(Annonce::class)
    //         ->findByMotCle();
    //     }
        
}
    