<?php

namespace AppBundle\Repository;

/**
 * ProprioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProprioRepository extends \Doctrine\ORM\EntityRepository
{
}
