<?php

namespace AppBundle\Repository;

/**
 * typeAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
