imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.annonce_photos: /uploads/photos/annonces

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# fos_user
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:                               # this lines
        mailer: fos_user.mailer.twig_swift # this lines
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

# Assetic
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:    [ ]
    java: C:\Program Files\Java\jdk1.8.0_65\bin\java.exe
    filters:
        cssrewrite: ~
        cssembed:
            jar: "%kernel.root_dir%/Resources/java/cssembed.jar"        
            yui_js:
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        lessphp:
            file: "%kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php"   
            apply_to: ".less$"
    assets:
        jquery_js:
            inputs:
                - "%kernel.root_dir%/../vendor/components/jquery/jquery.min.js"            
            filters: [?yui_js]
            output: js/jquery.min.js
        bootstrap_css:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less"
            filters:
                - lessphp
                - cssrewrite
            output: css/bootstrap.css            

        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js"
            filters: [?yui_js]
            output: js/bootstrap.js             
        fonts_glyphicons_eot:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.eot"
            output: "fonts/glyphicons-halflings-regular.eot"
        fonts_glyphicons_svg:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.svg"
            output: "fonts/glyphicons-halflings-regular.svg"
        fonts_glyphicons_ttf:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.ttf"
            output: "fonts/glyphicons-halflings-regular.ttf"
        fonts_glyphicons_woff:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.woff"

            output: "fonts/glyphicons-halflings-regular.woff"

#EasyAdmin
easy_admin:
    list:
        actions:
            - { name: 'edit', icon: 'pencil' }
    site_name: 'Carcassonne <em style="font-size: 80%;">Immo.</em>'
    list:
        max_results: 30
    show:
        max_results: 20    
    design:
        brand_color: '#62667F'
        # form_theme: [ 'horizontal', 'VichUploaderBundle:Form:fields.html.twig']
        menu:
            - { entity: 'User', icon: 'user' }
            - { entity: 'Annonce', icon: 'buysellads' }
            - { entity: 'Proprio', icon: 'address-card' }
            - { entity: 'TypeAnnonce', icon: 'folder-open' }
    entities:
        User:
            class: AppBundle\Entity\User
            form:
                fields:
                    - username
                    - prenom
                    - nom
                    - tel
                    - email
                    - password
                    - enabled
            list:
                title: L'agent immobilier
                fields:
                    - username
                    - prenom
                    - nom
                    - tel
                    - email
                    - enabled
        Annonce:
            class: AppBundle\Entity\Annonce
            list:
                title: Les Annonces
                fields:
                    - titre
                    - prix
                    - nbre_Piece
                    - { property: 'photo', type: 'image', base_path: '%app.path.annonce_photos%' }
                    - description
                    - agent
                    - typeAnnonce
                    - proprio
            form:
                fields:
                    - titre
                    - prix
                    - nbre_Piece
                    - { property: 'imageFile', type: 'vich_image' }
                    - description
                    - agent
                    - typeAnnonce
                    - proprio
        TypeAnnonce:
            class: AppBundle\Entity\TypeAnnonce
            list:
                title: Le type d'Annonce
                fields:
                    - { property: 'titre', label: 'Type' }
            form:
                title: Créer un type d'annonce
                fields:
                    - { type: 'group', css_class: 'col-sm-8' }
                    - { property: 'titre', label: 'Titre', type_options: {required: true} }
        Proprio:
            class: AppBundle\Entity\Proprio
            list:
                title: Les clients / propriétaires
                fields:
                    - { property: 'prenom', label: 'Prénom' }
                    - { property: 'nom', label: 'Nom' }
                    - { property: 'tel', label: 'Tel' }

# VichUploader
vich_uploader: 
    db_driver: orm 
    mappings: 
        annonce_photos: 
            uri_prefix: '%app.path.annonce_photos%' 
            upload_destination: '%kernel.root_dir%/../web/uploads/photos/annonces' 
            namer: vich_uploader.namer_uniqid


